/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-red": "#ba1a1a",
        "on-tertiary-container": "#cd8e2e",
        "primary-fixed": "#c9ead7",
        "on-error-container": "#93000a",
        "secondary-fixed": "#c3ecd2",
        "outline-variant": "#c2c8c2",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#adcebc",
        "tertiary": "#2c1a00",
        "surface-container-highest": "#d9d4c8",
        "surface-variant": "#dfe4de",
        "on-surface-variant": "#3b423d",
        "surface-container": "#eae6dc",
        "obsidian-scrim": "rgba(21, 26, 23, 0.78)",
        "secondary": "#416652",
        "surface-dim": "#d7dbd6",
        "secondary-container": "#c0e9cf",
        "outline": "#727974",
        "inverse-surface": "#2c322e",
        "on-tertiary-fixed-variant": "#633f00",
        "vellum-bg": "#f8f6f0",
        "primary": "#042217",
        "surface-container-high": "#e5e9e4",
        "tertiary-container": "#482d00",
        "on-primary-container": "#82a291",
        "sage-fill": "#d3e0d8",
        "on-surface": "#181d1a",
        "on-secondary-fixed-variant": "#294e3b",
        "background": "#f6fbf5",
        "on-secondary-fixed": "#002112",
        "surface-card-subtle": "#f2efe9",
        "on-background": "#181d1a",
        "tertiary-fixed-dim": "#feb956",
        "inverse-on-surface": "#edf2ec",
        "surface-container-low": "#f0f5ef",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#291800",
        "on-primary-fixed-variant": "#304d3f",
        "amber-container": "#ffddb4",
        "tertiary-fixed": "#ffddb4",
        "amber-on-container": "#633f00",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#a7d0b7",
        "outline-border": "#6b736d",
        "surface-card": "#ffffff",
        "on-primary": "#ffffff",
        "surface-bright": "#f6fbf5",
        "primary-container": "#1b382b",
        "on-secondary-container": "#456a56",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#476556",
        "surface": "#f6fbf5",
        "on-primary-fixed": "#022015",
        "outline-hairline": "#e5e0d5",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "inverse-primary": "#adcebc"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "space-xs": "0.25rem",
        "margin": "1rem",
        "gutter": "1rem",
        "space-sm": "0.5rem",
        "space-md": "1rem"
      },
      fontFamily: {
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg-mobile": ["Newsreader", "serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Newsreader", "serif"],
        "latin-name": ["Newsreader", "serif"],
        "display-lg": ["Newsreader", "serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "title-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Newsreader", "serif"]
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "38px", letterSpacing: "-0.015em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "700" }],
        "body-md": ["15px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "0em", fontWeight: "500" }],
        "latin-name": ["16px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
        "display-lg": ["40px", { lineHeight: "46px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0.005em", fontWeight: "400" }],
        "title-md": ["17px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "500" }]
      }
    }
  },
  plugins: [],
}
